[workspace]
resolver = "2"
members = [
    "mn-ab-parser",
    # "crates/math",
    # "crates/code_logic",
    # "crates/ui",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Joachim Koerfer"]
license = "MIT"
publish = false

[workspace.dependencies]
# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.228"

# GUI Ecosystem
eframe = "0.33.2"
egui = "0.33.2"

# Intra-workspace dependencies
# parser = { path = "mn-ab-parser" }
# math = { path = "crates/math" }
# code_logic = { path = "crates/code_logic" }