use markdown::mdast::Node;

pub fn node_name(node: &Node) -> &str {
    match node {
        Node::Root(_) => "Root",
        Node::BlockQuote(_) => "BlockQuote",
        Node::FootnoteDefinition(_) => "FootnoteDefinition",
        Node::MdxJsxFlowElement(_) => "MdxJsxFlowElement",
        Node::List(_) => "List",
        Node::MdxjsEsm(_) => "MdxjsEsm",
        Node::Toml(_) => "Toml",
        Node::Yaml(_) => "Yaml",
        Node::Break(_) => "Break",
        Node::InlineCode(_) => "InlineCode",
        Node::InlineMath(_) => "InlineMath",
        Node::Delete(_) => "Delete",
        Node::Emphasis(_) => "Emphasis",
        Node::MdxTextExpression(_) => "MdxTextExpression",
        Node::FootnoteReference(_) => "FootnoteReference",
        Node::Html(_) => "Html",
        Node::Image(_) => "Image",
        Node::ImageReference(_) => "ImageReference",
        Node::MdxJsxTextElement(_) => "MdxJsxTextElement",
        Node::Link(_) => "Link",
        Node::LinkReference(_) => "LinkReference",
        Node::Strong(_) => "Strong",
        Node::Text(_) => "Text",
        Node::Code(_) => "Code",
        Node::Math(_) => "Math",
        Node::MdxFlowExpression(_) => "MdxFlowExpression",
        Node::Heading(_) => "Heading",
        Node::Table(_) => "Table",
        Node::ThematicBreak(_) => "ThematicBreak",
        Node::TableRow(_) => "TableRow",
        Node::TableCell(_) => "TableCell",
        Node::ListItem(_) => "ListItem",
        Node::Definition(_) => "Definition",
        Node::Paragraph(_) => "Paragraph",
        _ => "unknown",
    }
}
