#include "widgets.h"
#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui_internal.h"

namespace RichText {
    // AbstractWidget
    bool AbstractWidget::buildAndAddChars(std::vector<WrapCharPtr>&) { 
       return true;
    }
    void AbstractWidget::draw(Draw::DrawList&  draw_list, float& cursor_y_pos, float x_offset, const Rect& boundaries) {
        x_offset += m_style.h_margins.x;
        cursor_y_pos += m_style.v_margins.y;

        m_position.x = x_offset;
        m_position.y = cursor_y_pos;
        float current_y_pos = cursor_y_pos;

        x_offset += m_style.h_paddings.x;
        cursor_y_pos += m_style.v_paddings.x;

        for (auto ptr : m_childrens) {
            ptr->draw(draw_list, cursor_y_pos, x_offset, boundaries);
        }

        cursor_y_pos += m_style.v_paddings.y;
        m_dimensions.x = m_window_width - x_offset;
        m_dimensions.y = cursor_y_pos - current_y_pos;

        cursor_y_pos += m_style.v_margins.y;
    }
    void AbstractWidget::buildWidget() {}
    void AbstractWidget::setWidth(float width) {
        m_window_width = width;
        for (auto ptr : m_childrens) {
            ptr->setWidth(width);
        }
    }

    // AbstractBlock
    void AbstractBlock::draw(Draw::DrawList&  draw_list, float& cursor_y_pos, float x_offset, const Rect& boundaries) {
        // Margins should added to offset, as they aren't counted in the block dimension
        x_offset += m_style.h_margins.x;
        cursor_y_pos += m_style.v_margins.y;

        m_position.x = x_offset;
        m_position.y = cursor_y_pos;
        float current_y_pos = cursor_y_pos;

        x_offset += m_style.h_paddings.x;
        cursor_y_pos += m_style.v_paddings.x;

        // buildWidget uses m_position, so we must call this function after setting m_position
        buildWidget();

        ImVec2 padding_before(m_style.h_paddings.x, m_style.v_paddings.x);

        // Draw all the chars generated by the block
        if (isInsideRectY(m_position, boundaries)) {
            for (auto ptr : m_draw_chars) {
                ptr->draw(draw_list, m_position + padding_before);
            }
        }
        // Draw all childrens (spans)
        for (auto ptr : m_childrens) {
            if (ptr->m_category != C_SPAN) {
                break;
            }
            ptr->draw(draw_list, cursor_y_pos, x_offset, boundaries);
        }
        // Update cursor from wrapper
        cursor_y_pos += m_wrapper.getHeight() + m_style.v_margins.x;
        // Draw all childrens (blocks)
        for (auto ptr : m_childrens) {
            if (ptr->m_category == C_BLOCK)
                ptr->draw(draw_list, cursor_y_pos, x_offset, boundaries);
        }

        current_y_pos += m_style.v_paddings.y;
        m_dimensions.x = m_window_width - x_offset;
        m_dimensions.y = cursor_y_pos - current_y_pos;
        current_y_pos += m_style.v_margins.y;

        m_show_boundaries = true;
        if (m_show_boundaries) {
            auto cursor_pos = ImGui::GetCursorScreenPos();
            ImVec2 p_min = cursor_pos + m_position;
            ImVec2 p_max = cursor_pos + m_position + m_dimensions;
            draw_list->AddRect(p_min, p_max, Colors::blue);
        }
        // Draw background
        if (m_style.bg_color != Colors::transparent) {
            draw_list.SetCurrentChannel(0);
            auto cursor_pos = ImGui::GetCursorScreenPos();
            ImVec2 p_min = cursor_pos + m_position;
            ImVec2 p_max = cursor_pos + m_position + m_dimensions;
            draw_list->AddRectFilled(p_min, p_max, m_style.bg_color, 5.f);
        }
    }
    void AbstractBlock::buildWidget() {
        if (m_widget_dirty) {
            m_wrap_chars.clear();
            m_draw_chars.clear();

            bool success = true;
            
            bool ret = build_chars();
            if (!ret)
                success = false;

            for (auto ptr : m_childrens) {
                if (ptr->m_category != C_SPAN) {
                    break;
                }
                auto res = ptr->buildAndAddChars(m_wrap_chars);
                if (!res) {
                    success = false;
                }
            }
            m_wrapper.clear();
            float internal_size = m_window_width - m_position.x;
            m_wrapper.setWidth(internal_size);
            m_wrapper.setLineSpace(m_style.line_space);
            m_wrapper.setString(m_wrap_chars);
            if (success)
                m_widget_dirty = false;
        }
    }
    void AbstractBlock::setWidth(float width) {
        float internal_size = m_dimensions.x - m_style.h_paddings.x - m_style.h_paddings.y;
        m_wrapper.setWidth(internal_size);
        m_window_width = width;
        for (auto ptr : m_childrens) {
            ptr->setWidth(width);
        }
    }
}